services:
  fpm:
    image: "template/fpm:0.1.0"
    build:
      context: ./.docker/fpm
    command: "/usr/bin/supervisord --nodaemon -c /etc/supervisord.conf"
    volumes:
      - ./backend:/var/www/html
  nginx:
    image: nginx:alpine
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./backend:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:-laravel}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-password}"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD" ]
      retries: 3
      timeout: 5s
  node:
    image: node:20.5-alpine
    working_dir: /app
